### PR TITLE
fixed type dropdown form for add-collectible and edit-collectible

### PR DESCRIPTION
**Pull request by tomki1**
fixed add-collectible and edit-collectible type dropdown
for add-collectible:
-all fields are required

for edit-collectible:
-requires collectible_id and at least one other field (name or type/attributes or picture)
-if user selects a type to edit, it is required to fill out all the attirbutes for that corresponding type

### CODE REVIEW

**Review by notkimroberts — APPROVED** [review]
LGTM.

**Review by jhhlim — CHANGES_REQUESTED** [review]
I got an error after adding a new colletcible - INVALID NAME Error: Invalid name
    at C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\routes\addcollectible.js:207:14
    at Layer.handle [as handle_request] (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\limja\Desktop\Capstone CS 467\collectors-trading-platform\node_modules\express\lib\router\index.js:47:12)

**Review by jhhlim — CHANGES_REQUESTED** [review]
I pushed my changes to this , please review and approve them for validation of name.

**Review by jhhlim — APPROVED** [review]
looks good!

**Pull request merged**
