### PR TITLE
Collectible integrate

### PR DESCRIPTION
**Pull request by jhhlim**
This PR fixes word-wrap for name in Collectibles tab and adds the update quantity UI. I have not yet started the functionality piece of it but will work on that next week.

**UPDATE: I have implemented admin functionality for add new collectible and edit collectible based on user admin status when registering. Please test this and advise if any changes/updates needed.

1. Fixes word wrap
2. UI update for collectibles tab - has, wants, trade and update button on all collectibles
3. Starting work for update / insert (in progress)
4. Also added the dropdown for Admin status - Register, not yet fully implemented functionality but will complete next week
5. fixed "blank submission" issue using regex
6. Confirm password should match before registering
**7. Implemented admin functionality throughout website.

### CODE REVIEW

**Review by notkimroberts — APPROVED** [review]

**Review by tomki1 — CHANGES_REQUESTED** [review]
for edit collectible, I think we wouldn't want the admins to be able to edit collectibles they aren't the admin for. Can we block admins from editing collectible types that they aren't the admin for?

**Comment by jhhlim** [comment]
> for edit collectible, I think we wouldn't want the admins to be able to edit collectibles they aren't the admin for. Can we block admins from editing collectible types that they aren't the admin for?

This has been fixed. Please retest

**Comment by tomki1** [comment]
> > for edit collectible, I think we wouldn't want the admins to be able to edit collectibles they aren't the admin for. Can we block admins from editing collectible types that they aren't the admin for?
> 
> This has been fixed. Please retest

@jhhlim  I'm logged in as something15 who is admin type 3, and it is still letting me update the name for hot wheels and lego.

**Comment by jhhlim** [comment]
> > > for edit collectible, I think we wouldn't want the admins to be able to edit collectibles they aren't the admin for. Can we block admins from editing collectible types that they aren't the admin for?
> > 
> > 
> > This has been fixed. Please retest
> 
> @jhhlim I'm logged in as something15 who is admin type 3, and it is still letting me update the name and photo for hot wheels and lego. Also, if I change the type to Funko and try to update it to Funko as admin type 3, it just loads forever.

I am unable to reproduce this issue. I logged in as something15 who is admin 3 (pusheen), I edited collectible Id: 15 which is type: lego and it throws an error. The behavior is correct. Please pull the recent changes if you have not done so already

**Review by notkimroberts — APPROVED** [review]

**Comment by jhhlim** [comment]
> for edit collectible, I think we wouldn't want the admins to be able to edit collectibles they aren't the admin for. Can we block admins from editing collectible types that they aren't the admin for?

this has been fixed

**Review by tomki1 — CHANGES_REQUESTED** [review]
Im logged in as something22, and when I try to update the name of collectible_id 20 which is type lego, then click submit, it says Please enter a name, select a type, and upload an image to update the collectible. Which I entered the name, so it shouldnt give me this error

**Comment by jhhlim** [comment]
> Im logged in as something22, and when I try to update the name of collectible_id 20 which is type lego, then click submit, it says Please enter a name, select a type, and upload an image to update the collectible. Which I entered the name, so it shouldnt give me this error.
> 
> For updating a collectible, the instructions are: "Collectible id and at least one other field are required". you need to just enter the collectible id, and one other field out of the 3, the 3 being name OR type/attributes OR photo. when you click on a type, it well tell you you need to fill out all the attributes for that type and its boxed so you know what you need to fill out.

hi Kimberly, I fixed this and tested ur exact steps. It should state that something22 does not have admin privileges to edit lego

**Comment by tomki1** [comment]
@jhhlim yes i see that that works now.  however, now I am logged in as something22 and edit a funko item, which is within my admin privelidge.  It lets me update the name when i in put the name only, but it also removes the attributes after the update.

image

**Comment by jhhlim** [comment]
> @jhhlim yes i see that that works now. however, now I am logged in as something22 and edit a funko item, which is within my admin privilege. It lets me update the name when i in put the name only, but it also removes the attributes after the update. I should be able to update one aspect of the item, name or picture or attributes without overwriting previous data for aspects I did not update.
> 
> image
> 
> Here is what we have now , it will just update the name or picture without overwriting. Thanks for the extensive testing!
> image

Hi @tomki1 were you able to confirm above. I accidentally edited your reply instead of creating a new one but this has been fixed. Thanks for the extensive testing.

**Comment by tomki1** [comment]
When I enter a non-existent collectible_id, and then click submit in edit-collectible, the page loads forever and never loads anything 
image

If I just enter a valid collectible_id for the valid admin type, then click submit, it loads the page as if it updated something.  I think we need to add the error message telling the user you need to edit at least one other field, because basically they are only submitting a collectible_id with no other info in the form without getting any error.

**Review by tomki1 — CHANGES_REQUESTED** [review]
please see above comment

**Comment by jhhlim** [comment]
> please see above comment

will review.

**Comment by jhhlim** [comment]
> please see above comment

fixed

**Review by tomki1 — CHANGES_REQUESTED** [review]
image
I am logged in as pokemon admin, if I select a type that's not pokemon, it gives me error: Please enter a name or upload an image to update the collectible.  That is not the right error message.  whether I enter something or nothing after selecting the wrong type, it should just say you don't have the privilege to update that to that type (something along those lines).

**Comment by jhhlim** [comment]
> image
> I am logged in as pokemon admin, if I select a type that's not pokemon, it gives me error: Please enter a name or upload an image to update the collectible. That is not the right error message. whether I enter something or nothing after selecting the wrong type, it should just say you don't have the privilege to update that to that type (something along those lines).
> 
> image
> I am pokemon admin and want to change pokemon item photo, input pokemon item id and select photo then hit submit. screen never changes, it just loads forever

got rid of excess code and updated the code. did base tests and registered new account and edited with success / failure each individual item + by name only, name + photo, name + type, type only, type + no attributes, type + attributes.

Should work now..

**Pull request closed without merging**
