### PR TITLE
feat: filtering on profile, collectible, collector, trade match pages

### PR DESCRIPTION
**Pull request by notkimroberts**
This PR adds type filtering to the user's profile page. One thing that needs to be fixed is after filters the checkbox don't stick. I'll look into it.

### CODE REVIEW

**Review by tomki1 — APPROVED** [review]
@notkimroberts  awesome, it works but for some reason http://localhost:3000/profile/list shows up in image format and not the table format anymore. I'm not sure why. We need to fix that when the filters are added to the other pages

**Review by jhhlim — COMMENTED** [review]
looks good on the profile page. Will wait for profile/list issue to be fixed

**Review by jhhlim — APPROVED** [review]

**Comment by notkimroberts** [comment]
@jhhlim @tomki1 I added filtering to `/collector/:id`, `/collector/list/:id`, `/collector/trade/:id`, and `/collector/trade/images/:id` routes. Please re-verify this works as expected. There can be some odd route precedence things going on so test that I haven't broken any other hyperlinks. I had one instance of `collectible/:id` breaking so had to move that to the top of the file.

**Review by jhhlim — CHANGES_REQUESTED** [review]
search collectible button broke. please review routes/collectible.js , it was working before

**Comment by notkimroberts** [comment]
@jhhlim Fixed.

**Review by jhhlim — APPROVED** [review]

**Pull request merged**
