### PR TITLE
added filter to collectible page

### PR DESCRIPTION
**Pull request by tomki1**
-can filter collectibles by type
-filter function on purposely disappears if on a single collectible's page or after searching for a collectible.  This is because clicking filter would just show all collectibles of a certain type and not take into account the search

### CODE REVIEW

**Review by notkimroberts — APPROVED** [review]
LGTM. Just need to fix merge conflicts.

**Review by jhhlim — CHANGES_REQUESTED** [review]
Filter not working consecutive try. 

*Filter only works first time around. After filtering for lego and getting results staying on the page and trying to filter again for a different value such as pusheen--seeing blank values and the filter refreshes and goes back to default 'lego'.

**Comment by tomki1** [comment]
> Filter not working consecutive try.
> 
> *Filter only works first time around. After filtering for lego and getting results staying on the page and trying to filter again for a different value such as pusheen--seeing blank values and the filter refreshes and goes back to default 'lego'.

There is nothing in the pusheen category so that is why it is blank when you filter by pusheen.  Lego happens to be the first type option so every time you go to the collectible page with a filter, it will show lego in the dropdown (even if it's not filtered by lego).  I don't know how to add a blank placeholder option for the filter so it wont always show lego. If someone knows how, that would be something good to fix

**Review by jhhlim — APPROVED** [review]
Got it. Possibly adding a none option for default value would work (it can say 'None' or it can be blank). will look into that

**Pull request merged**
